### ISSUE TITLE
USER STORY: Search Content

### ISSUE THREAD

**Issue by OSawani** [OSawani/zinc-flake-coatings-webapp#10]
As a **user**, I want to **search for content**, so that **I can find information quickly**.

## Acceptance Criteria:
* Users can enter keywords in a search bar to find content.
* Relevant results are displayed based on the search query.
* Search results are grouped by chapters or categories.
* Users can easily navigate through grouped results.
* Keywords matching the search query are highlighted in the results.
* Highlighting helps users identify relevant information quickly.
* If there are no results, the user gets feedback that there is no matching results. 
## Tasks:
- [x] Implement search bar (3 SP)
- [x] Handle Search Queries (5SP)
- [x] Display search results grouped by chapters (3 SP)
- [x] Highlight matched keywords in results (2 SP)
- [x] Navigation to content pages (2SP)
- [x] No search results (2SP)
- [x] Paginate search results (3SP)
